### ISSUE TITLE
Approval section - Admin settings

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#1]
Add a new section on the admin page that allows to:

- See new approval requests
- Click user row and navigate to their profile page 
- Approve or remove approval in one click
- Search through the list using email of display name

Admin rights section can serve as inspiration and partially be reused

Branch `enhancement/add-approval`

**Comment by ettorebevilacqua** [comment]
Hy I test my invite

**Comment by aleclofabbro** [comment]
@brumasribera  shall we remove `See new approval requests` from the feature list, as "user publishing approval request" is not a MN core feature

**Comment by brumasribera** [comment]
Probably, I believe I added it to our custom package, no?
