### ISSUE TITLE
Review webpack bundle config to reduce bundle size

### ISSUE THREAD

**Issue by aleclofabbro** [moodle/moodlenet#11]
having reviewed much of webpack/webapp-deps in #9 :
invest some time to investigate and attempt to fix webpack vendor bundle weight issue

**Comment by aleclofabbro** [comment]
@brumasribera : from `extensions-manager`'s `ExtensionInfo.tsx` removed `react-syntax-highlighter` so far: that package loads all languages parsers, taking >1MB 
layout didn't worsen at all (for now), as there are no code blocks in READMEs (so far)
let's find a way to load parsers dynamically 

the same issue (minor entity) applies to `moment` : it loads all languages.

**Comment by aleclofabbro** [comment]
@brumasribera I see the dependency `lottie` is also quite heavy: it alone takes 613KB+

**Comment by aleclofabbro** [comment]
resized extensions-manager's `package-icon-#`s to 128px

**Comment by aleclofabbro** [comment]
added `babel-plugin-direct-import` for `@mui` treeshaking

**Comment by brumasribera** [comment]
> @brumasribera I see the dependency `lottie` is also quite heavy: it alone takes 613KB+

And for now is not used, but will probably will soon on an upload animation in the resource page. 

I just could find any other alternative to show a svg animation. 

I could try to use a gif or find a lighter alternative.

**Comment by aleclofabbro** [comment]
webapp is 1MB lighter : ~2.6MB 
- ~ 1.7MB vendor chunk
- < 26KB each application chunk
