### ISSUE TITLE
Improve multiselect dropdown

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#37]
Add an option to allow multiselect dropdowns to close after a selection is made, and not to remain opened.

This is already working in Storybook, as can be seen below. 

So @aleclofabbro, we need to find out what might be happening on the other side.

https://github.com/moodle/moodlenet/assets/5635059/a356dbef-a063-43ba-9926-3cd9ecc15ddc

**Comment by aleclofabbro** [comment]
let multi dropdown auto close on selection, add an option to keep it opened
