### ISSUE TITLE
Show snackbars anywhere

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#43]
Allow snackbars to be shown even if the component that triggered it is gone. So that it can stay on the screen at any time and context.

**Comment by aleclofabbro** [comment]
I suggest to approach the issue as in [`Modal`](https://github.com/moodle/moodlenet/blob/master/packages/component-library/src/webapp/ui/components/atoms/Modal/Modal.tsx), useing [`createPortal()`](https://react.dev/reference/react-dom/createPortal) api

**Comment by brumasribera** [comment]
Of course! 😊
