### ISSUE TITLE
unavailable (unpublished) content result as blank spaces in card lists

### ISSUE THREAD

**Issue by aleclofabbro** [moodle/moodlenet#44]
user featured entities ( likes, bookmarks, follows, resources in collection ) and later any gets unavailable (unpublished), the item key still returns to webapp, resulting in a blank where the card should be

**Comment by aleclofabbro** [comment]
it would ideal to show an "unavailable entity card"
for the moment we can filter out them in the server

**Comment by brumasribera** [comment]
Why do you prefer unavailable cards? I find it a bit weird from the user point of view to start seeing not available elements. 😅

**Comment by aleclofabbro** [comment]
as a user I would be more confused seeing item-cards disappearing and re-appearing in my lists ( bookmarks, followings, resources in collections )..
I'd consider more meaningful to see a "currently unavailable/unpublished"  item-card, and have the choice either to keep it waiting for it to be back available, or to remove it from the list ..
