### ISSUE TITLE
Notify user when AI autofill fails

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#49]
We need to change the `autofillState` of the resource state when the AI autofill process goes wrong, and assign it to an `ai-error`.

So that we can display a snackbar informing the user.

This should only show the first time the page is visited, or appear directly is the page remained open.

![Image](https://github.com/moodle/moodlenet/assets/5635059/305d068c-5f19-4005-be2a-5f72835dfe4b)

**Comment by aleclofabbro** [comment]
fixed in another way:
issues we faced so far were not due to ai generation, but to some subtle exceptions in text extraction procedures
we fixed those subtleties, and added fallbacks
