### ISSUE TITLE
Implement user moderation inside MoodleNet

### ISSUE THREAD

**Issue by moodler** [moodle/moodlenet#55]
Rough steps:

1) @annakrassa  starts with a sample interface of the best way based on her experience 
2) @brumasribera  refines the interface for a module in MoodleNet ([Find designs here](https://www.figma.com/file/tA9fkhLCzjf9SXDofRRVQd/MoodleNet-4.0?type=design&node-id=3114%3A1612&mode=design&t=YJkDC3vPaF5QapKB-1))
3) @aleclofabbro  implements

**Comment by aleclofabbro** [comment]
let's keep in mind:

1. User publishing permission editing is currently available as a core functionality in `User-Menu->Admin->User` 
2. The current `user approval request workflow` (aka `create 5 resources to request publishing permission`) baked by Jira is implemented in an [additional package](https://www.npmjs.com/package/@moodlenet/mn-central-jira-simple-moderations), to avoid leaking a `moodle.net` specific use-case into the software core

**Comment by moodler** [comment]
Anna's first https://docs.google.com/drawings/d/1HxWBC0tgC7cJozrDIkiBNPH5f1sAqVrk0ByFHG9PFVU/edit

**Comment by annakrassa** [comment]
The title here "Implement user approvals inside MoodleNet" seems a bit confusing to me. The draw was about Reporting user profiles, not approvals...

**Comment by moodler** [comment]
@brumasribera can you link your designs here?

**Comment by annakrassa** [comment]
Hi team, 

Here is a suggestion for the [Auto-approval flow](https://docs.google.com/drawings/d/1x5yxo_XLM1UeYBykP7g7kt-hPHDlrKH-BUQgZvAfzTo/edit?usp=sharing)

**Comment by aleclofabbro** [comment]
closing in favor of #62 , as base user moderation have been implemented in  #61
