### ISSUE TITLE
Report users

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#61]
- [x] Allow users to report other user profiles

- [x] Allow admins to manage reported profiles

    - [x] Show reported users on a table
    
    - [x] Sort columns
         - [x] Display name, alphabetic asc, desc
         - [x] Flags, numeric asc, desc
         - [x] Last flag, date recent, old
         - [x] Main reason, alphabetically, each click shows a different reason on top
         - [x] Status, , alphabetically, each click shows a different reason on top

    - [x] Allow actions
         - [x] Ignore flags
         - [x] Approve/unapprove user
         - [x] Delete user

    - [x] Show modals
         - [x] Flags   
         - [x] Reasons
         - [x] Status

Check also @annakrassa [design proposal ](https://docs.google.com/drawings/d/1HxWBC0tgC7cJozrDIkiBNPH5f1sAqVrk0ByFHG9PFVU/edit)

![Image](https://github.com/moodle/moodlenet/assets/5635059/576bd3ad-c81f-4b52-aef7-1aef791b5013)

**Comment by aleclofabbro** [comment]
closed with https://github.com/moodle/moodlenet/commit/2bd505b8a59a5b7dc53576e7d659bd826d58ec4c
