### ISSUE TITLE
Auto-approval flow

### ISSUE THREAD

**Issue by brumasribera** [moodle/moodlenet#62]
Allow users to be approved after uploading 3 resources. 

Send them emails after each upload to keep them on track and motivated.

- [x] Users automatically become publisher after 3 resources uploaded

- [x] Emails
     - [x] Welcome email - improve, mention approval requirements
     - [x] 1st contribution, only 2 left!
     - [x] 2nd contribution, only 1 left!
     - [x] Congratulations - You are now a Publisher on MoodleNet

Check @annakrassa [design proposal](https://docs.google.com/drawings/d/1x5yxo_XLM1UeYBykP7g7kt-hPHDlrKH-BUQgZvAfzTo/edit)

**Comment by aleclofabbro** [comment]
check also #55 for more info and discussions

**Comment by moodler** [comment]
Makes sense to recognise their existing resources yes, all the steps you outlined.

existing 0 - send them the new welcome email
