### ISSUE TITLE
Delete inactive users account

### ISSUE THREAD

**Issue by aleclofabbro** [moodle/moodlenet#68]
Add a configuration option to automatically delete inactive users account 
if users has not logged in the system for `configured-inactivity-days`, their account and _unpublished_ contribution are automatically deleted
`configured-notification-days` before, the system must send the user an informative email about the imminent deletion of their account, giving them the opportunity to log in and interrupt the deletion procedure

**Comment by moodler** [comment]
Just delete the user's account (which has private info) -don't delete their content automatically though.
