### ISSUE TITLE
access_rule_base.php not found in Moodle 4.1

### ISSUE THREAD

**Issue by Bhanuka94** [moodle/moodlenet#69]
Due to missing the access_rule_base.php file, the Moodle Quiz settings is not working properly. This is an issue in Moodle 4.1.10+ version

In other moodle versions, the access_rule_base.php is found in mod/quiz/classes/local/ directory and the Quiz settings appears.

In Moodle 4.1, only structure folder is available. No reports folder or the above mentioned php file.

![Screenshot_7](https://github.com/moodle/moodlenet/assets/51482638/6dca402c-567e-4fa9-add5-6b990a0bc6e4)

**Comment by aleclofabbro** [comment]
hey @Bhanuka94 ,
this is MoodleNet project repository, 
you likely want to post this issue in [Moodle issues Tracker](https://tracker.moodle.org/projects/MDL/issues)
